---
require: rubocop-rake
AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayCopNames: true
  Exclude:
    - "**/node_modules/**/*"
    - "**/target/**/*"
    - "**/vendor/**/*"
Layout/LineLength:
  Enabled: true
  Exclude:
    - "**/Rakefile"
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
