---
name: Merge
"on":
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  labels:
    name: Labels
    runs-on: ubuntu-latest

    steps:
      - uses: mheap/github-action-required-labels@cc7a79fadbba6ed1d6f0efd70707e7b8bf7e6910 # v5.2.0
        with:
          mode: exactly
          count: 0
          labels: "S-do-not-merge, S-wip"
